{
 "title": "New dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queue",
    "query": " SELECT DISTINCT CONCAT('queue=','\"',q.ext_number,'\"','queue_name=','\"',q.name,'\"') FROM `queues` q JOIN `departments` d ON q.`department_id` = d.`id` JOIN `profiles` p \nON d.`id` = p.`department_id` LEFT JOIN `users` u ON p.`id` = u.`profile_id` WHERE  '${__user.login}' = u.`username` OR 1<=(SELECT COUNT(*) FROM `users` u JOIN `groups_users` gu ON u.`id` = gu.user_id \nJOIN `groups_special_permissions` gsp ON gu.group_id = gsp.group_id  JOIN `special_permissions` sp \nON gsp.special_permission_id = sp.id WHERE  '${__user.login}' = u.`username`  AND sp.name = 'Agent Supervisor')"
   }
  ]
 },
 "panels": [
  {
   "title": "کل تماس ها",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tgui",
     "rawSql": "SELECT COUNT(*) FROM tgui.recordings t WHERE  $__timeFilter(t.date_created_ts) /*AND  t.`call_direction` = 'IN' */\r\nAND f_queue_get_by_extnumber($queue) = queue_id"
    }
   ]
  },
  {
   "title": "تماس پاسخ داده",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tgui",
     "rawSql": "SELECT COUNT(*) FROM tgui.recordings t WHERE $__timeFilter(t.date_created_ts) -- AND t.`call_status` = 'ANSWER'\r\n AND f_queue_get_by_extnumber($queue) = queue_id AND t.to_profile_id IS NOT NULL "
    }
   ]
  },
  {
   "title": "میانگین مدت مکالمه",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tgui",
     "rawSql": "SELECT IFNULL(SEC_TO_TIME(ROUND(AVG(t.duration))),0)  FROM `recordings` t WHERE f_queue_get_by_extnumber($queue) = queue_id AND $__timeFilter(t.date_created_ts)"
    }
   ]
  },
  {
   "title": "answer rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tgui",
     "rawSql": "SELECT\r\n  IFNULL(\r\n    (SELECT\r\n      COUNT(*)\r\n    FROM\r\n      tgui.recordings t\r\n    WHERE $__timeFilter(t.date_created_ts)\r\n      -- AND t.`call_status` = 'ANSWER'\r\n      AND t.to_profile_id IS NOT NULL\r\n     -- AND t.`call_direction` = 'IN'\r\n      AND f_queue_get_by_extnumber($queue) = queue_id\r\n        ) /\r\n    (SELECT\r\n      COUNT(*)\r\n    FROM\r\n      tgui.recordings t\r\n    WHERE t.`date_created_ts` >= DATE(NOW())\r\n      -- AND t.`call_direction` = 'IN'\r\n      AND f_queue_get_by_extnumber($queue) = queue_id\r\n        \r\n  ),0) * 100"
    }
   ]
  },
  {
   "title": "میانگین زمان انتظار",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tgui",
     "rawSql": "  SELECT IFNULL(SEC_TO_TIME(ROUND(AVG(t.`hold_time`))),0) AS 'max_hold' FROM `recordings` t WHERE  f_queue_get_by_extnumber($queue) = queue_id  AND $__timeFilter(t.date_created_ts) AND to_profile_id IS NOT NULL"
    }
   ]
  },
  {
   "title": "تماس پاسخ نداده",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tgui",
     "rawSql": "SELECT count(*) FROM recordings t WHERE f_queue_get_by_extnumber($queue) = queue_id  and   $__timeFilter(t.date_created_ts)   AND to_profile_id IS  NULL"
    }
   ]
  },
  {
   "title": "بیشترین زمان انتظار قبل از قطع تماس",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tgui",
     "rawSql": "SELECT ifnull(SEC_TO_TIME(MAX(t.`hold_time`)),0) AS 'max_hold' FROM `recordings` t WHERE f_queue_get_by_extnumber($queue) = queue_id  and   $__timeFilter(t.date_created_ts)   AND to_profile_id IS  NULL"
    }
   ]
  },
  {
   "title": "missed rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tgui",
     "rawSql": "SELECT\r\n  IFNULL(\r\n    (SELECT\r\n      COUNT(*)\r\n    FROM\r\n      tgui.recordings t\r\n    WHERE $__timeFilter(t.date_created_ts)\r\n      -- AND t.`call_status` = 'ANSWER'\r\n      AND t.to_profile_id IS  NULL\r\n     -- AND t.`call_direction` = 'IN'\r\n      AND f_queue_get_by_extnumber($queue) = queue_id\r\n        ) /\r\n    (SELECT\r\n      COUNT(*)\r\n    FROM\r\n      tgui.recordings t\r\n    WHERE t.`date_created_ts` >= DATE(NOW())\r\n      -- AND t.`call_direction` = 'IN'\r\n      AND f_queue_get_by_extnumber($queue) = queue_id\r\n        \r\n  ),0) * 100"
    }
   ]
  },
  {
   "title": "Miss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tgui",
     "rawSql": "SELECT \r\n     count( CASE WHEN f_miss_call(r.date_start_ts, r.date_created_ts, r.caller_id)=3 THEN 1 ELSE NULL END )\r\n  FROM recordings r\r\n WHERE $__timeFilter(r.date_created_ts)\r\n   AND $__timeFilter(r.date_created_ts)\r\n  AND f_queue_get_by_extnumber($queue) = queue_id"
    }
   ]
  }
 ]
}