{
 "title": "Queue Info",
 "description": "پس از  مطالعه دقیق نیازمندی های مدیران شرکت های طرف قرارداد شرکت ارتباطات بین المللی هدف از ایجاد این داشبورد فراهم کردن امکان نظارت کلی  بر تمامی صف های مجموعه در قالب یک پنل برای سوپروایزر ها قرار داده شد تا روند نظارت راحت تر انجام شود.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "All Queues by choice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Queues",
     "type": "table",
     "description": "نمایش درصد موفقیت پاسخگویی در صف",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "dataset": "cacti",
       "rawSql": "CALL p_full_queue_stats_with_answered_rate_multi('8400,4411,8300')\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "All Queues ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "total",
     "type": "table",
     "description": "نمایش درصد موفقیت پاسخگویی در صف",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "cacti",
       "rawSql": "CALL sp_get_wallboard_queues_metrics_with_agents()  "
      }
     ]
    }
   ]
  },
  {
   "title": "4411",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": " اپراتور ",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "dataset": "cacti",
       "rawSql": "CALL p_full_queue_stats_with_answered_rate('4411')\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "8500",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": " خدمات بیمه اتومبیل ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "cacti",
       "rawSql": "CALL p_full_queue_stats_with_answered_rate('8500')"
      }
     ]
    }
   ]
  },
  {
   "title": "4900",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": " انتقادات و پیسنهادات ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "cacti",
       "rawSql": "CALL p_full_queue_stats_with_answered_rate('4900')"
      }
     ]
    }
   ]
  },
  {
   "title": "8300",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": " سایر خدمات و محصولات بیمه ای ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 248 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "cacti",
       "rawSql": "CALL p_full_queue_stats_with_answered_rate('8300')"
      }
     ]
    }
   ]
  }
 ]
}