{
 "title": "overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "6s",
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "صف",
    "query": "SELECT DISTINCT CONCAT('queue=\"', q.ext_number, '\"','queue_name=\"', q.name, '\"') \nFROM queues q\nJOIN departments d ON q.department_id = d.id\nWHERE EXISTS (\n    SELECT 1\n    FROM profiles p\n    JOIN users u ON p.id = u.profile_id\n    WHERE p.department_id = d.id AND u.username = '${__user.login}'\n)\nOR q.department_id IN (\n    SELECT dp.department_id\n    FROM departments_profiles dp\n    JOIN profiles p ON dp.profile_id = p.id\n    JOIN users u ON p.id = u.profile_id\n    WHERE u.username = '${__user.login}'\n)\nOR EXISTS (\n    SELECT 1\n    FROM users u\n    JOIN groups_users gu ON u.id = gu.user_id\n    JOIN groups_special_permissions gsp ON gu.group_id = gsp.group_id  \n    JOIN special_permissions sp ON gsp.special_permission_id = sp.id\n    WHERE u.username = '${__user.login}' AND sp.name = 'Queues Admin'\n)\n"
   },
   { "name": "hold_time", "label": "hold_time", "query": "10,20,30,40,50,60" }
  ]
 },
 "panels": [
  {
   "title": "امتیاز",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT  CONCAT(p.first_name,' ',p.`last_name`) AS 'کارشناس',\r\n        AVG(recordings.`agentScore`) AS 'متوسط امتیاز'\r\n               FROM recordings\r\n              JOIN `profiles` p\r\n              ON `recordings`.`to_profile_id` = p.id\r\n\r\n              WHERE date_created_ts >= curdate() \r\n\r\n                AND f_queue_get_by_extnumber($queue) = queue_id \r\n\r\n                AND to_profile_id IS NOT NULL\r\n\t\t\t\t\r\n                and recordings.`agentScore` is not null\r\n                \r\n              GROUP BY to_agent\r\n              order by 2\r\n              LIMIT 5\r\n\t\t\t  \r\n\t\t\t  "
    }
   ]
  },
  {
   "title": "توقف",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 0 },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "\r\nSELECT tt.pause AS 'مدت توقف',\r\n CONCAT(p.first_name,' ',p.`last_name`)  AS 'کاربر',\r\n SUBSTR(`BASE64_DECODE`(aq.`PausedReason`),6)AS 'وضعیت'\r\nFROM  `asterisk_members` aq\r\nJOIN (\r\nSELECT\r\n  TIMEDIFF(NOW() , MAX(t.`time`)) AS pause,\r\n  t.agent\r\nFROM\r\n  `agent_logs` t\r\n  WHERE t.`time` >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n  AND t.`action_type` = 'pause'\r\n  GROUP BY t.`agent`\r\n   ) tt\r\n  ON tt.agent =  SUBSTR(aq.NAME,7)\r\n  JOIN `queues` q\r\n  ON aq.`Queue` = q.`ext_number`\r\n  JOIN agents a \r\n  ON a.agentid = SUBSTR(aq.NAME,7)\r\n  JOIN `profiles` p \r\n  ON a.profile_id = p.id\r\n  WHERE  aq.`paused` = 1\r\nAND  f_queue_get_by_extnumber($queue) = q.`id`\r\n  \r\n"
    }
   ]
  },
  {
   "title": "انتظار در صف",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 0 },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT CallerIDNum AS  \"تماس از\",\r\nConnectedLineNum AS \"تماس به\",\r\nsec_to_time(WAIT) AS \"انتظار\",\r\nPOSITION AS \"موقعیت\"\r\n FROM asterisk_queue_entries t\r\n JOIN `queues` q\r\n ON t.`Queue` = q.`ext_number`\r\n WHERE f_queue_get_by_extnumber($queue) = q.`id` "
    }
   ]
  },
  {
   "title": "تماس",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 13, "y": 0 },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT\r\n  oc.call_to AS \"شماره داخلی\",\r\n  oc.answer_time AS \"مدت زمان مکالمه\",\r\n  oc.to_profile AS \"کاربر\",\r\n  incall.COUNT AS \"تماس ورودی\",\r\n  outcall.COUNT AS \"تماس خروجی\",\r\n  login.login AS \"لاگین صف\",\r\n  DATE_FORMAT(login.time, '%H:%i:%s') AS \"زمان لاگین\",\r\n  oc.call_from AS \"تماس\"\r\nFROM\r\n  (\r\n    SELECT\r\n      CONCAT(p.first_name, ' ', p.last_name) AS \"to_profile\",\r\n      t.call_to_exten AS call_to,\r\n      CONCAT(t.call_from, '=>') AS call_from,\r\n      TIMEDIFF(NOW(), t.answer_time) AS answer_time,\r\n      t.to_agent AS agentid\r\n    FROM online_calls t\r\n      JOIN agents a ON t.to_agent = a.agentid\r\n      JOIN profiles p ON a.profile_id = p.id\r\n    WHERE t.call_direction = 'IN'\r\n      AND t.status = 'Talking'\r\n      AND to_profile_id IS NOT NULL\r\n      AND f_queue_get_by_extnumber($queue) = t.queue_id\r\n  ) oc\r\n  LEFT JOIN\r\n  (\r\n    SELECT\r\n      TIMEDIFF(NOW(), MAX(t.time)) AS login,\r\n      MAX(t.time) AS time,\r\n      t.agent\r\n    FROM agent_logs t\r\n      JOIN agents a ON t.agent = a.agentid\r\n      JOIN agents_queues aq ON a.id = aq.agent_id\r\n    WHERE t.action_type = 'login'\r\n      AND aq.login = 1\r\n      AND t.time >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND f_queue_get_by_extnumber($queue) = aq.queue_id\r\n    GROUP BY t.agent\r\n  ) login ON oc.agentid = login.agent\r\n  LEFT JOIN\r\n  (\r\n    SELECT to_agent AS agentid, COUNT(recordings.id) AS COUNT\r\n    FROM recordings\r\n    WHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND recordings.server_id = '101'\r\n      AND f_queue_get_by_extnumber($queue) = recordings.queue_id\r\n      AND to_profile_id IS NOT NULL\r\n      AND to_agent IS NOT NULL\r\n    GROUP BY to_agent\r\n  ) incall ON oc.agentid = incall.agentid\r\n  LEFT JOIN\r\n  (\r\n    SELECT from_agent AS agentid, COUNT(recordings.id) AS COUNT\r\n    FROM recordings\r\n    WHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND recordings.server_id = '101'\r\n      AND call_direction = 'OUT'\r\n      AND trunk_id IS NOT NULL\r\n      AND from_profile_id IS NOT NULL\r\n      AND from_agent IN (\r\n        SELECT DISTINCT a.agentid\r\n        FROM agents a\r\n        WHERE a.id IN (\r\n          SELECT agent_id FROM agents_queues aq\r\n          WHERE f_queue_get_by_extnumber($queue) = aq.queue_id\r\n        )\r\n      )\r\n    GROUP BY from_agent\r\n  ) outcall ON oc.agentid = outcall.agentid\r\n\r\n\r\nUNION\r\n\r\n\r\nSELECT\r\n  oc.call_from AS \"شماره داخلی\",\r\n  oc.answer_time AS \"مدت زمان مکالمه\",\r\n  oc.to_profile AS \"کاربر\",\r\n  incall.COUNT AS \"تماس ورودی\",\r\n  outcall.COUNT AS \"تماس خروجی\",\r\n  login.login AS \"لاگین صف\",\r\n  DATE_FORMAT(login.time, '%H:%i:%s') AS \"زمان لاگین\",\r\n  oc.call_from2 AS \"تماس\"\r\nFROM\r\n  (\r\n    SELECT\r\n      CONCAT(p.first_name, ' ', p.last_name) AS \"to_profile\",\r\n      t.call_from,\r\n      CONCAT(t.call_to, '<=') AS call_from2,\r\n      TIMEDIFF(NOW(), t.answer_time) AS answer_time,\r\n      t.from_agent AS agentid\r\n    FROM online_calls t\r\n      JOIN agents a ON t.from_agent = a.agentid\r\n      JOIN profiles p ON t.from_profile_id = p.id\r\n    WHERE t.call_direction = 'OUT'\r\n      AND t.status = 'Talking'\r\n      AND t.from_agent IN (\r\n        SELECT DISTINCT a.agentid\r\n        FROM agents a\r\n        WHERE a.id IN (\r\n          SELECT agent_id FROM agents_queues aq\r\n          WHERE f_queue_get_by_extnumber($queue) = aq.queue_id\r\n        )\r\n      )\r\n      AND from_profile_id IS NOT NULL\r\n  ) oc\r\n  LEFT JOIN\r\n  (\r\n    SELECT\r\n      TIMEDIFF(NOW(), MAX(t.time)) AS login,\r\n      MAX(t.time) AS time,\r\n      t.agent\r\n    FROM agent_logs t\r\n      JOIN agents a ON t.agent = a.agentid\r\n      JOIN agents_queues aq ON a.id = aq.agent_id\r\n    WHERE t.action_type = 'login'\r\n      AND aq.login = 1\r\n      AND t.time >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND f_queue_get_by_extnumber($queue) = aq.queue_id\r\n    GROUP BY t.agent\r\n  ) login ON oc.agentid = login.agent\r\n  LEFT JOIN\r\n  (\r\n    SELECT to_agent AS agentid, COUNT(recordings.id) AS COUNT\r\n    FROM recordings\r\n    WHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND recordings.server_id = '101'\r\n      AND f_queue_get_by_extnumber($queue) = recordings.queue_id\r\n      AND to_profile_id IS NOT NULL\r\n      AND to_agent IS NOT NULL\r\n    GROUP BY to_agent\r\n  ) incall ON oc.agentid = incall.agentid\r\n  LEFT JOIN\r\n  (\r\n    SELECT from_agent AS agentid, COUNT(recordings.id) AS COUNT\r\n    FROM recordings\r\n    WHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND recordings.server_id = '101'\r\n      AND call_direction = 'OUT'\r\n      AND trunk_id IS NOT NULL\r\n      AND from_profile_id IS NOT NULL\r\n      AND from_agent IN (\r\n        SELECT DISTINCT a.agentid\r\n        FROM agents a\r\n        WHERE a.id IN (\r\n          SELECT agent_id FROM agents_queues aq\r\n          WHERE f_queue_get_by_extnumber($queue) = aq.queue_id\r\n        )\r\n      )\r\n    GROUP BY from_agent\r\n  ) outcall ON oc.agentid = outcall.agentid\r\n\r\n\r\nUNION\r\n\r\n\r\nSELECT\r\n  oc.call_to AS \"شماره داخلی\",\r\n  oc.answer_time AS \"مدت زمان مکالمه\",\r\n  oc.to_profile AS \"کاربر\",\r\n  incall.COUNT AS \"تماس ورودی\",\r\n  outcall.COUNT AS \"تماس خروجی\",\r\n  login.login AS \"لاگین صف\",\r\n  DATE_FORMAT(login.time, '%H:%i:%s') AS \"زمان لاگین\",\r\n  oc.call_from2 AS \"تماس\"\r\nFROM\r\n  (\r\n    SELECT\r\n      CONCAT(p.first_name, ' ', p.last_name) AS \"to_profile\",\r\n      t.call_to,\r\n      CONCAT(t.call_from, '=>') AS call_from2,\r\n      TIMEDIFF(NOW(), t.answer_time) AS answer_time,\r\n      t.to_agent AS agentid\r\n    FROM online_calls t\r\n      JOIN agents a ON t.to_agent = a.agentid\r\n      JOIN profiles p ON a.profile_id = p.id\r\n    WHERE t.call_direction = 'OUT'\r\n      AND t.status = 'Talking'\r\n      AND t.to_agent IN (\r\n        SELECT DISTINCT a.agentid\r\n        FROM agents a\r\n        WHERE a.id IN (\r\n          SELECT agent_id FROM agents_queues aq\r\n          WHERE f_queue_get_by_extnumber($queue) = aq.queue_id\r\n        )\r\n      )\r\n      AND from_profile_id IS NOT NULL\r\n      AND to_profile_id IS NOT NULL\r\n  ) oc\r\n  LEFT JOIN\r\n  (\r\n    SELECT\r\n      TIMEDIFF(NOW(), MAX(t.time)) AS login,\r\n      MAX(t.time) AS time,\r\n      t.agent\r\n    FROM agent_logs t\r\n      JOIN agents a ON t.agent = a.agentid\r\n      JOIN agents_queues aq ON a.id = aq.agent_id\r\n    WHERE t.action_type = 'login'\r\n      AND aq.login = 1\r\n      AND t.time >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND f_queue_get_by_extnumber($queue) = aq.queue_id\r\n    GROUP BY t.agent\r\n  ) login ON oc.agentid = login.agent\r\n  LEFT JOIN\r\n  (\r\n    SELECT to_agent AS agentid, COUNT(recordings.id) AS COUNT\r\n    FROM recordings\r\n    WHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND recordings.server_id = '101'\r\n      AND f_queue_get_by_extnumber($queue) = recordings.queue_id\r\n      AND to_profile_id IS NOT NULL\r\n      AND to_agent IS NOT NULL\r\n    GROUP BY to_agent\r\n  ) incall ON oc.agentid = incall.agentid\r\n  LEFT JOIN\r\n  (\r\n    SELECT from_agent AS agentid, COUNT(recordings.id) AS COUNT\r\n    FROM recordings\r\n    WHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND recordings.server_id = '101'\r\n      AND call_direction = 'OUT'\r\n      AND trunk_id IS NOT NULL\r\n      AND from_profile_id IS NOT NULL\r\n      AND from_agent IN (\r\n        SELECT DISTINCT a.agentid\r\n        FROM agents a\r\n        WHERE a.id IN (\r\n          SELECT agent_id FROM agents_queues aq\r\n          WHERE f_queue_get_by_extnumber($queue) = aq.queue_id\r\n        )\r\n      )\r\n    GROUP BY from_agent\r\n  ) outcall ON oc.agentid = outcall.agentid;\r\n"
    }
   ]
  },
  {
   "title": "تماس پاسخ داده",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "adm", "rawSql": "SELECT f_calls_handled($queue)" }
   ]
  },
  {
   "title": "کل تماس ها",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "adm", "rawSql": "SELECT f_total_calls($queue)" }
   ]
  },
  {
   "title": "کارشناسان آزاد",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "select f_available_agents($queue)"
    }
   ]
  },
  {
   "title": "لاگین در صف",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "adm", "rawSql": "select f_login_agents($queue)" }
   ]
  },
  {
   "title": "زمان پاسخگویی",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT CONCAT(p.first_name, ' ', p.`last_name`) AS \"کارشناس\",SEC_TO_TIME(cast(e.duraton as integer)) AS \"زمان پاسخگویی\",IFNULL(al.t,0) AS miss\r\nFROM (\r\nSELECT incall.name_o  AS e , (IFNULL(incall.duration,0) + IFNULL(outcall.duration,0)) AS duraton\r\nFROM (\r\nSELECT\r\n  to_agent AS name_o,\r\n  SUM(recordings.duration) AS duration\r\nFROM\r\n  recordings\r\n  JOIN `profiles` p\r\n    ON `recordings`.`to_profile_id` = p.id\r\nWHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n  AND recordings.server_id = '101'\r\n  AND f_queue_get_by_extnumber($queue) = queue_id \r\n  AND to_profile_id IS NOT NULL\r\nGROUP BY to_agent) incall\r\n\r\n LEFT  JOIN (SELECT\r\n     from_agent AS name_o,\r\n  SUM(recordings.duration) AS duration\r\n    FROM\r\n      recordings\r\n      JOIN `profiles` p\r\n    ON `recordings`.`to_profile_id` = p.id\r\n    WHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND recordings.server_id = '101'\r\n      AND call_direction = 'OUT'\r\n      AND trunk_id IS NOT NULL\r\n      AND from_profile_id IS NOT NULL\r\n      AND from_agent IN (SELECT DISTINCT a.agentid FROM agents a WHERE a.id IN (SELECT agent_id FROM `agents_queues` aq WHERE  f_queue_get_by_extnumber($queue) = aq.queue_id ))\r\n    GROUP BY from_agent)outcall\r\n     ON incall.name_o = outcall.name_o\r\n     WHERE incall.name_o IS NOT NULL \r\n   UNION \r\n   SELECT outcall.name_o AS e  , (IFNULL(incall.duration,0) + IFNULL(outcall.duration,0)) AS duration\r\nFROM (\r\nSELECT\r\n  to_agent AS name_o,\r\n  SUM(recordings.duration) AS duration\r\nFROM\r\n  recordings\r\n  JOIN `profiles` p\r\n    ON `recordings`.`to_profile_id` = p.id\r\nWHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n  AND recordings.server_id = '101'\r\n  AND f_queue_get_by_extnumber($queue) = queue_id \r\n  AND to_profile_id IS NOT NULL\r\nGROUP BY to_agent) incall\r\n\r\n RIGHT   JOIN (SELECT\r\n     from_agent AS name_o,\r\n  SUM(recordings.duration) AS duration\r\n    FROM\r\n      recordings\r\n      JOIN `profiles` p\r\n    ON `recordings`.`to_profile_id` = p.id\r\n    WHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND recordings.server_id = '101'\r\n      AND call_direction = 'OUT'\r\n      AND trunk_id IS NOT NULL\r\n      AND from_profile_id IS NOT NULL\r\n      AND from_agent IN (SELECT DISTINCT a.agentid FROM agents a WHERE a.id IN (SELECT agent_id FROM `agents_queues` aq WHERE  f_queue_get_by_extnumber($queue) = aq.queue_id ))\r\n    GROUP BY from_agent)outcall\r\n     ON incall.name_o = outcall.name_o\r\n     WHERE outcall.name_o IS NOT NULL )e\r\n     LEFT JOIN (SELECT COUNT(*) AS t , al.`agent` FROM agent_logs al WHERE al.`time` > DATE(NOW()) AND al.`action_type` = 'miss' GROUP BY al.`agent`) al\r\n     ON e.e = al.`agent`\r\n     JOIN agents a ON e.e = a.`agentid` \r\n     JOIN `profiles` p ON a.`profile_id` = p.`id`\r\n\tUNION \t\r\n     \r\n     SELECT CONCAT(p.first_name, ' ', p.`last_name`) AS \"کارشناس\",SEC_TO_TIME(cast(e.duraton As integer)) AS \"زمان پاسخگویی\",IFNULL(al.t,0) AS miss\r\nFROM (\r\nSELECT incall.name_o  AS e , (IFNULL(incall.duration,0) + IFNULL(outcall.duration,0)) AS duraton\r\nFROM (\r\nSELECT\r\n  to_agent AS name_o,\r\n  SUM(recordings.duration) AS duration\r\nFROM\r\n  recordings\r\n  JOIN `profiles` p\r\n    ON `recordings`.`to_profile_id` = p.id\r\nWHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n  AND recordings.server_id = '101'\r\n  AND f_queue_get_by_extnumber($queue) = queue_id \r\n  AND to_profile_id IS NOT NULL\r\nGROUP BY to_agent) incall\r\n\r\n LEFT  JOIN (SELECT\r\n     from_agent AS name_o,\r\n  SUM(recordings.duration) AS duration\r\n    FROM\r\n      recordings\r\n      JOIN `profiles` p\r\n    ON `recordings`.`to_profile_id` = p.id\r\n    WHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND recordings.server_id = '101'\r\n      AND call_direction = 'OUT'\r\n      AND trunk_id IS NOT NULL\r\n      AND from_profile_id IS NOT NULL\r\n      AND from_agent IN (SELECT DISTINCT a.agentid FROM agents a WHERE a.id IN (SELECT agent_id FROM `agents_queues` aq WHERE  f_queue_get_by_extnumber($queue) = aq.queue_id ))\r\n    GROUP BY from_agent)outcall\r\n     ON incall.name_o = outcall.name_o\r\n     WHERE incall.name_o IS NOT NULL \r\n   UNION \r\n   SELECT outcall.name_o AS e  , (IFNULL(incall.duration,0) + IFNULL(outcall.duration,0)) AS duration\r\nFROM (\r\nSELECT\r\n  to_agent AS name_o,\r\n  SUM(recordings.duration) AS duration\r\nFROM\r\n  recordings\r\n  JOIN `profiles` p\r\n    ON `recordings`.`to_profile_id` = p.id\r\nWHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n  AND recordings.server_id = '101'\r\n  AND f_queue_get_by_extnumber($queue) = queue_id \r\n  AND to_profile_id IS NOT NULL\r\nGROUP BY to_agent) incall\r\n\r\n RIGHT   JOIN (SELECT\r\n     from_agent AS name_o,\r\n  SUM(recordings.duration) AS duration\r\n    FROM\r\n      recordings\r\n      JOIN `profiles` p\r\n    ON `recordings`.`to_profile_id` = p.id\r\n    WHERE date_created_ts >= DATE_FORMAT(NOW(), '%Y/%m/%d')\r\n      AND recordings.server_id = '101'\r\n      AND call_direction = 'OUT'\r\n      AND trunk_id IS NOT NULL\r\n      AND from_profile_id IS NOT NULL\r\n      AND from_agent IN (SELECT DISTINCT a.agentid FROM agents a WHERE a.id IN (SELECT agent_id FROM `agents_queues` aq WHERE  f_queue_get_by_extnumber($queue) = aq.queue_id ))\r\n    GROUP BY from_agent)outcall\r\n     ON incall.name_o = outcall.name_o\r\n     WHERE outcall.name_o IS NOT NULL )e\r\n     RIGHT JOIN (SELECT COUNT(*) AS t , al.`agent` FROM agent_logs al WHERE al.`time` > DATE(NOW()) AND al.`action_type` = 'miss' GROUP BY al.`agent`) al\r\n     ON e.e = al.`agent`\r\n     JOIN agents a ON e.e = a.`agentid` \r\n     JOIN `profiles` p ON a.`profile_id` = p.`id`\r\n     \r\n     \r\n"
    }
   ]
  },
  {
   "title": "answer rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "adm", "rawSql": "SELECT f_answerd_rate($queue)" }
   ]
  },
  {
   "title": "کارشناسان فعال",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "call p_active_agent(f_queue_get_by_extnumber($queue))"
    }
   ]
  },
  {
   "title": "میانگین مدت مکالمه",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT IFNULL(SEC_TO_TIME(ROUND(AVG(t.duration))),0)  FROM `recordings` t WHERE f_queue_get_by_extnumber($queue)  = queue_id AND t.`date_created_ts` >= DATE(NOW())"
    }
   ]
  },
  {
   "title": "منتظر در صف",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT f_calls_in_queue($queue)"
    }
   ]
  },
  {
   "title": "نسبت تماس های ورودی صف به کل تماس ها",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT\r\n$__timeGroupAlias(t.`date_created_ts` + interval 30 minute, 30m),\r\nCOUNT(*) AS \"calls_queue\"\r\nFROM tgui.recordings t\r\nWHERE\r\n$__timeFilter(t.`date_created_ts` ) and $__timeGroup(t.`date_created_ts` + interval 30 minute, 30m) < unix_timestamp(now())\r\nAND (f_queue_get_by_extnumber($queue) IN ( queue_id ))\r\nGROUP BY 1\r\nORDER BY $__timeGroup(t.`date_created_ts` + interval 30 minute, 30m)\r\n\r\n\r\n"
    },
    {
     "dataset": "adm",
     "rawSql": "SELECT\r\n$__timeGroupAlias(t.`date_created_ts` + interval 30 minute, 30m),\r\nCOUNT(*) AS \"total_calls\"\r\nFROM tgui.recordings t\r\nWHERE\r\n$__timeFilter(t.`date_created_ts`)\r\nAND (call_direction='IN')  and $__timeGroup(t.`date_created_ts` + interval 30 minute, 30m) < unix_timestamp(now())\r\nGROUP BY 1\r\nORDER BY $__timeGroup(t.`date_created_ts` + interval 30 minute, 30m)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "میانگین زمان انتظار",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT f_average_wait_time($queue)"
    }
   ]
  },
  {
   "title": "بیشترین زمان انتظار",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT f_longest_wait_time($queue)"
    }
   ]
  },
  {
   "title": "Miss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT \r\n     count( CASE WHEN f_miss_call(r.date_start_ts, r.date_created_ts, r.caller_id)=3 THEN 1 ELSE NULL END )\r\n  FROM recordings r\r\n WHERE r.date_created_ts >= DATE(NOW())\r\n   AND r.date_created_ts < NOW()\r\n  AND (f_queue_get_by_extnumber($queue) IN ( queue_id ))"
    }
   ]
  },
  {
   "title": "سطح سرویس $hold_time ثانیه",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT IFNULL((SELECT\r\n  COUNT(*)\r\nFROM\r\n  tgui.recordings t\r\nWHERE t.`date_created_ts` >= DATE(NOW())\r\n  AND t.`call_status` = 'ANSWER'\r\n  AND t.`call_direction` = 'IN'\r\n  AND f_queue_get_by_extnumber($queue) IN (queue_id)\r\n  AND t.`hold_time` <= $hold_time)/\r\n(SELECT\r\n  COUNT(*)\r\nFROM\r\n  tgui.recordings t\r\nWHERE t.`date_created_ts` >= DATE(NOW())\r\n  AND t.`call_status` = 'ANSWER'\r\n  AND t.`call_direction` = 'IN'\r\n  AND f_queue_get_by_extnumber($queue) IN (queue_id)),0) *100 as 'sl'\r\n  \r\n    "
    }
   ]
  },
  {
   "title": "سطح سرویس ساعتی",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "cacti",
     "rawSql": "SELECT \r\n    CONCAT(LPAD(h.hour, 2, '0'), ':00-', LPAD(h.hour, 2, '0'), ':59') AS hour_label,\r\n    IFNULL(\r\n        ROUND(\r\n            COUNT(CASE WHEN r.hold_time <= $hold_time THEN 1 END) * 100.0 / COUNT(r.date_created_ts),\r\n            0\r\n        ),\r\n        0\r\n    ) AS percentage\r\nFROM (\r\n    SELECT 0 AS hour UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3\r\n    UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7\r\n    UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11\r\n    UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15\r\n    UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19\r\n    UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23\r\n) AS h\r\nLEFT JOIN recordings r\r\n    ON HOUR(r.date_created_ts) = h.hour\r\n    AND r.date_created_ts >= CURDATE()\r\n    AND r.call_direction = 'in'\r\n    AND r.queue_id = f_queue_get_by_extnumber($queue)\r\nGROUP BY h.hour\r\nORDER BY h.hour;\r\n"
    }
   ]
  },
  {
   "title": "FCR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT (SELECT IFNULL(SUM(tt.ee),0) FROM ((SELECT COUNT(*) AS ee\r\nFROM  recordings t\r\nWHERE t.`date_created_ts` >= DATE(NOW())\r\n  AND t.`call_direction` = 'IN'  AND LENGTH(t.`caller_id`) > 4  AND  f_queue_get_by_extnumber($queue) in(t.`queue_id`) \r\n  GROUP BY t.caller_id\r\n  HAVING COUNT(*) = 1))tt) / (SELECT COUNT(*) FROM tgui.recordings t WHERE t.`date_created_ts` >= DATE(NOW()) /*AND  t.`call_direction` = 'IN' */\r\nAND ( f_queue_get_by_extnumber($queue)  IN ( t.queue_id) )) *100"
    }
   ]
  },
  {
   "title": "قطع در صف",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "adm",
     "rawSql": "SELECT IFNULL((SELECT \r\n      COUNT(CASE WHEN f_miss_call(r.date_start_ts, r.date_created_ts, r.caller_id)=2 THEN 1 ELSE NULL END ) \r\n  FROM recordings r\r\n WHERE r.date_created_ts >= DATE(NOW())\r\n   AND r.date_created_ts < NOW()\r\n  AND (f_queue_get_by_extnumber($queue) IN ( queue_id ))\r\n   AND (r.to_agent IS NULL)),0)/\r\nIFNULL((SELECT COUNT(*) FROM tgui.recordings t WHERE t.`date_created_ts` >= DATE(NOW()) \r\n/*AND t.`call_direction` = 'IN'*/ AND (f_queue_get_by_extnumber($queue) IN ( queue_id ))),1) *100 AS 'abandoned',IFNULL((SELECT \r\n      COUNT(CASE WHEN f_miss_call(r.date_start_ts, r.date_created_ts, r.caller_id)=2 THEN 1 ELSE NULL END ) \r\n  FROM recordings r\r\n WHERE r.date_created_ts >= DATE(NOW())\r\n   AND r.date_created_ts < NOW()\r\n  AND (f_queue_get_by_extnumber($queue) IN ( queue_id ))\r\n   AND (r.to_agent IS NULL) /*SELECT COUNT(*) FROM tgui.recordings t WHERE t.`date_created_ts` >= DATE(NOW()) \r\n AND ($queue IN ( queue_id ) ) AND t.to_profile_id IS  NULL*/),0) AS COUNT"
    }
   ]
  },
  {
   "title": "درصد موفقیت تماس های ترنسفری",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cacti",
     "rawSql": "SELECT \r\n    COUNT(r1.id) AS total_calls,\r\n    r1.call_status\r\nFROM recordings r\r\nINNER JOIN recordings r1 \r\n    ON r.transfered_to_id = r1.tgui_unique\r\nWHERE \r\n    r.call_direction = 'in'\r\n    AND r.duration >= 1\r\n    AND r.transfered_to != ''\r\n    AND r.date_created_ts >= CURDATE()\r\n    AND f_queue_get_by_extnumber($queue) = r.queue_id\r\n    AND r.transfered_to != f_queue_get_by_extnumber(4411)  -- exclude calls transferred to queue 4411\r\nGROUP BY \r\n    r1.call_status;\r\n"
    }
   ]
  }
 ]
}